name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build_apps:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK 3.1
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'
      
      - name: Restore App Dependencies
        run: |
          cd ./Apps
          dotnet restore

      - name: Build Apps
        run: |
          cd ./Apps
          dotnet build --configuration Release --no-restore
      
      - name: 'Upload ScriptSegmentation Files'
        uses: actions/upload-artifact@v2.2.4
        with:
          name: 'ScriptSegmentationFiles'
          path: 'Apps/ScriptSegmentation/bin/Release/netcoreapp3.1/*'
          retention-days: 30
      
      - name: 'Upload RemoteFileManager Files'
        uses: actions/upload-artifact@v2.2.4
        with:
          name: 'RemoteFileManagerFiles'
          path: 'Apps/RemoteFileManager/bin/Release/netcoreapp3.1/*'
          retention-days: 30

      - name: 'Upload WorkflowRunner Files'
        uses: actions/upload-artifact@v2.2.4
        with:
          name: 'WorkflowRunnerFiles'
          path: 'Apps/WorkflowRunner/bin/Release/netcoreapp3.1/*'
          retention-days: 30

  run_workflows:
    runs-on: windows-2019
    needs: build_apps
    steps:
    - name: Download WorkflowRunner Files
      uses: actions/download-artifact@v2.0.10
      with:
        name: WorkflowRunnerFiles
        path: 'WorkflowRunnerFiles'

    - name: Run Encode Workflow
      run: |
        cd WorkflowRunnerFiles
        ./WorkflowRunner.exe -t ${{ secrets.OAUTH_TOKEN }} -r ${{ github.ref }} -w ${{ secrets.ENCODE_WORKFLOW_ID }}

    - name: Run Merge Workflow
      run: |
        cd WorkflowRunnerFiles
        ./WorkflowRunner.exe -t ${{ secrets.OAUTH_TOKEN }} -r ${{ github.ref }} -w ${{ secrets.JOIN_WORKFLOW_ID }}