name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_apps:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Build Apps
          status: 'in_progress'
          sha: ${{ github.sha }}

      - name: Setup .NET Core SDK 3.1
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'
      
      - name: Restore App Dependencies
        run: |
          cd ./Apps
          dotnet restore

      - name: Build Apps
        run: |
          cd ./Apps
          dotnet build --configuration Release --no-restore
      
      - name: 'Upload ScriptSegmentation Files'
        uses: actions/upload-artifact@v2.2.4
        with:
          name: 'ScriptSegmentationFiles'
          path: 'Apps/ScriptSegmentation/bin/Release/netcoreapp3.1/*'
          retention-days: 30
      
      - name: 'Upload RemoteFileManager Files'
        uses: actions/upload-artifact@v2.2.4
        with:
          name: 'RemoteFileManagerFiles'
          path: 'Apps/RemoteFileManager/bin/Release/netcoreapp3.1/*'
          retention-days: 30

      - name: 'Upload WorkflowRunner Files'
        uses: actions/upload-artifact@v2.2.4
        with:
          name: 'WorkflowRunnerFiles'
          path: 'Apps/WorkflowRunner/bin/Release/netcoreapp3.1/*'
          retention-days: 30

      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Build Apps
          status: 'completed'
          conclusion: ${{ job.status }}
          sha: ${{ github.sha }}
      
      - name: 'Dispatch Encode Workflow'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ secrets.ENCODE_WORKFLOW_ID }}
          token: ${{ secrets.OAUTH_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref || github.head_ref }}