name: Encode

on:
  workflow_dispatch:
    inputs:
      clips_to_encode:
        description: 'JSON string of clips to be encoded. If omitted will use a test clip.'
        required: false
        default: '["clip1"]'
      segments:
        description: 'JSON string of  the amount of segments to splice and encode each clip. Must be a set of sequential numbers starting from 1. If omitted splice into 15 segments.'
        required: false
        default: '[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]'
      run_id:
        description: 'Run ID that triggered this run. Used to get artifacts. If omitted will take from last successful run on master branch.'
        required: false

jobs:
  send_status_check:
    runs-on: windows-2019
    steps:
      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Encode Files
          status: 'in_progress'

  encode_footage:
    runs-on: windows-2019
    needs: send_status_check
    strategy:
      matrix:
        clip: ${{fromJson(github.event.inputs.clips_to_encode)}}
        segment: ${{fromJson(github.event.inputs.segments)}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      
      - name: Download ScriptSegmentation Files
        uses: dawidd6/action-download-artifact@v2
        with:
          name: ScriptSegmentationFiles
          path: 'ScriptSegmentationFiles'
          workflow: build.yml
          run_id: ${{ github.event.inputs.run_id }}
        
      - name: Download RemoteFileManager Files
        uses: dawidd6/action-download-artifact@v2
        with:
          name: RemoteFileManagerFiles
          path: 'RemoteFileManagerFiles'
          workflow: build.yml
          run_id: ${{ github.event.inputs.run_id }}
      
      - name: Download Google Drive Credentials
        run: |
          cd RemoteFileManagerFiles
          New-Item -Path . -Name "credentials.json" -ItemType "file" -Value '${{ secrets.GOOGLE_DRIVE_SECRET }}'
      
      - name: Download Footage from Google Drive
        run: |
          cd RemoteFileManagerFiles
          ./RemoteFileManager.exe down ../Encoding Footage
      
      - name: Install Avisynth+
        run: |
          Move-Item -Path '.\AviSynth\ProgramFiles' -Destination 'C:\Program Files (x86)\AviSynth+' -force
          Move-Item -Path '.\AviSynth\System32\*' -Destination 'C:\Windows\System32' -force
          .\AviSynth\registry.bat
      
      - name: Install Lagarith Codec
        run: |
          cd ./Lagarith
          ./install.bat

      - name: Prepare input.avs file
        run: |
          cd ./Encoding
          Set-Content input.avs 'Import("../Encoding/${{matrix.clip}}.avs")'

      - name: Run Script Segmentation app
        run: |
          cd ScriptSegmentationFiles
          $json = ConvertFrom-Json -InputObject '${{github.event.inputs.segments}}'
          $length = echo Object.keys($json).Length
          ./ScriptSegmentation.exe $length[1] ../Encoding/final.avs ../Encoding/Segments

      - name: Encode Clip Segment
        run: |
          cd ./Encoding
          New-Item -Path 'Output' -ItemType Directory
          ./x264.exe --qp 10 -b 0 --input-range tv --range tv --output-csp i420 --colormatrix bt709 --output ./Output/${{matrix.segment}}.mkv "./Segments/${{matrix.segment}}.avs" --thread-input --output-depth 8

      - name: Upload Encoded Clip Segment
        run: |
          cd RemoteFileManagerFiles
          ./RemoteFileManager.exe up ../Encoding/Output "${{matrix.clip}}" ${{matrix.segment}}.mkv

  normalize_audio:
    needs: send_status_check
    runs-on: windows-2019
    strategy:
      matrix:
        clip: ${{fromJson(github.event.inputs.clips_to_encode)}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Download RemoteFileManager Files
        uses: dawidd6/action-download-artifact@v2
        with:
          name: RemoteFileManagerFiles
          path: 'RemoteFileManagerFiles'
          workflow: build.yml
          run_id: ${{ github.event.inputs.run_id }}
      
      - name: Download Google Drive Credentials
        run: |
          cd RemoteFileManagerFiles
          New-Item -Path . -Name "credentials.json" -ItemType "file" -Value '${{ secrets.GOOGLE_DRIVE_SECRET }}'
      
      - name: Download Footage from Google Drive
        run: |
          cd RemoteFileManagerFiles
          ./RemoteFileManager.exe down ../Encoding Footage

      - name: Install Avisynth+
        run: |
          Move-Item -Path '.\AviSynth\ProgramFiles' -Destination 'C:\Program Files (x86)\AviSynth+' -force
          Move-Item -Path '.\AviSynth\System32\*' -Destination 'C:\Windows\System32' -force
          .\AviSynth\registry.bat
      
      - name: Install Lagarith Codec
        run: |
          cd ./Lagarith
          ./install.bat
      
      - name: Extract FFmpeg
        run: |
          cd ./Encoding
          7z e ffmpeg.7z.001 -y

      - name: Prepare input.avs file
        run: |
          cd ./Encoding
          Set-Content input.avs 'Import("../Encoding/${{matrix.clip}}.avs")'
      
      - name: Extract Audio File
        run: |
          cd ./Encoding
          New-Item -Path 'Output' -ItemType Directory
          ./ffmpeg.exe -y -i ./final.avs ./Output/audio.wav
      
      - name: Run WaveGain
        run: |
          cd ./Encoding
          ./WaveGain.exe -y ./Output/audio.wav
      
      - name: Upload Normalized Audio
        run: |
          cd RemoteFileManagerFiles
          ./RemoteFileManager.exe up ../Encoding/Output "${{matrix.clip}}" audio.wav

  send_final_status_check:
    runs-on: windows-2019
    needs: ['encode_footage', 'normalize_audio']
    if: always()
    steps:
      - name: Escape Clips to Encode Input Parameter
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          $clips = '${{github.event.inputs.clips_to_encode}}'.Replace('"', '\"')
          Write-Host ::set-env name=escaped_clips::$clips

      - name: 'Dispatch Join Workflow'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ secrets.JOIN_WORKFLOW_ID }}
          token: ${{ secrets.OAUTH_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref || github.head_ref }}
          inputs: '{ "clips_to_encode": "${{env.escaped_clips}}", "run_id": "${{ github.event.inputs.run_id }}" }'
      
      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Encode Files
          status: 'completed'
          conclusion: ${{ job.status }}