name: Encode

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA-1 that triggered this run. Used to get artifacts. If omitted will take from last successful run on master branch.'
        required: false

jobs:
  send_status_check:
    runs-on: windows-2019
    steps:
      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Encode Files
          status: 'in_progress'

  encode_footage:
    runs-on: windows-2019
    needs: send_status_check
    strategy:
      matrix:
        clip: ["clip1", "clip2", "clip3", "clip4", "clip5", "clip6"]
        segment: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      
      - name: Download ScriptSegmentation Files
        uses: dawidd6/action-download-artifact@v2
        with:
          name: ScriptSegmentationFiles
          path: 'ScriptSegmentationFiles'
          workflow: build.yml
          commit: ${{ on.workflow_dispatch.inputs.commit_sha }}
        
      - name: Download RemoteFileManager Files
        uses: dawidd6/action-download-artifact@v2
        with:
          name: RemoteFileManagerFiles
          path: 'RemoteFileManagerFiles'
          workflow: build.yml
          commit: ${{ on.workflow_dispatch.inputs.commit_sha }}
      
      - name: Download Google Drive Credentials
        run: |
          cd RemoteFileManagerFiles
          New-Item -Path . -Name "credentials.json" -ItemType "file" -Value '${{ secrets.GOOGLE_DRIVE_SECRET }}'
      
      - name: Download Footage from Google Drive
        run: |
          cd RemoteFileManagerFiles
          ./RemoteFileManager.exe down ../Encoding Footage
      
      - name: Install Avisynth+
        run: |
          Move-Item -Path '.\AviSynth\ProgramFiles' -Destination 'C:\Program Files (x86)\AviSynth+' -force
          Move-Item -Path '.\AviSynth\System32\*' -Destination 'C:\Windows\System32' -force
          .\AviSynth\registry.bat
      
      - name: Install Lagarith Codec
        run: |
          cd ./Lagarith
          ./install.bat

      - name: Prepare input.avs file
        run: |
          cd ./Encoding
          Set-Content input.avs 'Import("../Encoding/${{matrix.clip}}.avs")'

      - name: Run Script Segmentation app
        run: |
          cd ScriptSegmentationFiles
          ./ScriptSegmentation.exe 4 ../Encoding/final.avs ../Encoding/Segments

      - name: Encode Clip Segment
        run: |
          cd ./Encoding
          New-Item -Path 'Output' -ItemType Directory
          ./x264.exe --qp 10 -b 0 --input-range tv --range tv --output-csp i420 --colormatrix bt709 --output ./Output/${{matrix.segment}}.mkv "./Segments/${{matrix.segment}}.avs" --thread-input --output-depth 8

      - name: Upload Encoded Clip Segment
        run: |
          cd RemoteFileManagerFiles
          ./RemoteFileManager.exe up ../Encoding/Output "${{matrix.clip}}" ${{matrix.segment}}.mkv

  normalize_audio:
    needs: send_status_check
    runs-on: windows-2019
    strategy:
      matrix:
        clip: ["clip1", "clip2", "clip3", "clip4", "clip5", "clip6"]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Download RemoteFileManager Files
        uses: dawidd6/action-download-artifact@v2
        with:
          name: RemoteFileManagerFiles
          path: 'RemoteFileManagerFiles'
          workflow: build.yml
          commit: ${{ on.workflow_dispatch.inputs.commit_sha }}
      
      - name: Download Google Drive Credentials
        run: |
          cd RemoteFileManagerFiles
          New-Item -Path . -Name "credentials.json" -ItemType "file" -Value '${{ secrets.GOOGLE_DRIVE_SECRET }}'
      
      - name: Download Footage from Google Drive
        run: |
          cd RemoteFileManagerFiles
          ./RemoteFileManager.exe down ../Encoding Footage

      - name: Install Avisynth+
        run: |
          Move-Item -Path '.\AviSynth\ProgramFiles' -Destination 'C:\Program Files (x86)\AviSynth+' -force
          Move-Item -Path '.\AviSynth\System32\*' -Destination 'C:\Windows\System32' -force
          .\AviSynth\registry.bat
      
      - name: Install Lagarith Codec
        run: |
          cd ./Lagarith
          ./install.bat
      
      - name: Extract FFmpeg
        run: |
          cd ./Encoding
          7z e ffmpeg.7z.001 -y

      - name: Prepare input.avs file
        run: |
          cd ./Encoding
          Set-Content input.avs 'Import("../Encoding/${{matrix.clip}}.avs")'
      
      - name: Extract Audio File
        run: |
          cd ./Encoding
          New-Item -Path 'Output' -ItemType Directory
          ./ffmpeg.exe -y -i ./final.avs ./Output/audio.wav
      
      - name: Run WaveGain
        run: |
          cd ./Encoding
          ./WaveGain.exe -y ./Output/audio.wav
      
      - name: Upload Normalized Audio
        run: |
          cd RemoteFileManagerFiles
          ./RemoteFileManager.exe up ../Encoding/Output "${{matrix.clip}}" audio.wav

  send_final_status_check:
    runs-on: windows-2019
    needs: ['encode_footage', 'normalize_audio']
    steps:
      - name: 'Dispatch Join Workflow'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ secrets.JOIN_WORKFLOW_ID }}
          token: ${{ secrets.OAUTH_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref || github.head_ref }}
          inputs: '{ "commit_sha": "${{ on.workflow_dispatch.inputs.commit_sha }}" }'
      
      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Encode Files
          status: 'completed'
          conclusion: ${{ job.status }}