name: Full Encode Flow

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  encode:
    runs-on: ubuntu-latest
    steps:
    - name: Run Build Pipeline
      run: echo "Hello World"
