name: Join

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Encode"]
    types: [completed]

jobs:
  merge_files:
    runs-on: windows-2019
    if: ${{ github.event.workflow_run.conclusion == '' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        clip: ["clip"]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      
      - name: Download RemoteFileManager Files
        uses: dawidd6/action-download-artifact@v2
        with:
          name: RemoteFileManagerFiles
          path: 'RemoteFileManagerFiles'
          workflow: build.yml
          workflow_conclusion: completed
          branch: master
      
      - name: Download Encoded Footage
        run: |
          cd RemoteFileManagerFiles
          ./RemoteFileManager.exe down ../Encoding/Output "${{matrix.clip}}-\d{1,}\.mkv|${{matrix.clip}}-audio\.wav"
      
      - name: Download Google Drive Credentials
        run: |
          cd RemoteFileManagerFiles
          New-Item -Path . -Name "credentials.json" -ItemType "file" -Value "$(GOOGLE_DRIVE_SECRET)"
      
      - name: Run MKV Merge
        run: |
          cd ./Encoding/Output
          $filenames = $($(Get-ChildItem $(pwd) -Filter *.mkv) -join " ")
          New-Item -Path 'Final' -ItemType Directory
          ../mkvmerge.exe -o Final/${{matrix.clip}}.mkv "./${{matrix.clip}}-audio.wav" '[' $filenames ']'

      - name: Upload Normalized Audio
        run: |
          cd RemoteFileManagerFiles
          ./RemoteFileManager.exe up ../Encoding/Output/Final